### ISSUE TITLE
発着両方存在する駅のEkijikokuの処理に間違いがある

### ISSUE THREAD

**Issue by KameLong** [route-builders/OudOperator#21]
5:18着、5:19発の駅の記述はoudファイル上で  
EkiJikoku=1;518/519  
となっており、「1;着時刻/発時刻」となっているが、このライブラリでは
「1;発時刻/着時刻」として解釈されているようです。

結果として、発着両方の時刻ある駅は全て逆転しています。

**Comment by up-tri** [comment]
closed #22
